# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(913, 448)
        MainWindow.setMinimumSize(QtCore.QSize(681, 365))
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_export_log = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export_log.setGeometry(QtCore.QRect(430, 230, 91, 23))
        self.btn_export_log.setObjectName("btn_export_log")
        self.le_log_export = QtWidgets.QLineEdit(self.centralwidget)
        self.le_log_export.setGeometry(QtCore.QRect(110, 230, 301, 20))
        self.le_log_export.setReadOnly(True)
        self.le_log_export.setObjectName("le_log_export")
        self.btn_devices = QtWidgets.QPushButton(self.centralwidget)
        self.btn_devices.setGeometry(QtCore.QRect(790, 230, 111, 23))
        self.btn_devices.setObjectName("btn_devices")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 230, 91, 16))
        self.label.setObjectName("label")
        self.btn_sys_prop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sys_prop.setGeometry(QtCore.QRect(20, 310, 101, 23))
        self.btn_sys_prop.setObjectName("btn_sys_prop")
        self.te_show = QtWidgets.QTextEdit(self.centralwidget)
        self.te_show.setGeometry(QtCore.QRect(10, 10, 891, 211))
        self.te_show.setReadOnly(True)
        self.te_show.setObjectName("te_show")
        self.btn_reboot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reboot.setGeometry(QtCore.QRect(670, 270, 101, 23))
        self.btn_reboot.setObjectName("btn_reboot")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 270, 91, 16))
        self.label_2.setObjectName("label_2")
        self.le_file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.le_file_path.setGeometry(QtCore.QRect(80, 270, 231, 20))
        self.le_file_path.setClearButtonEnabled(False)
        self.le_file_path.setObjectName("le_file_path")
        self.btn_push = QtWidgets.QPushButton(self.centralwidget)
        self.btn_push.setGeometry(QtCore.QRect(570, 270, 81, 23))
        self.btn_push.setObjectName("btn_push")
        self.btn_clear_info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_info.setGeometry(QtCore.QRect(240, 310, 91, 23))
        self.btn_clear_info.setObjectName("btn_clear_info")
        self.btn_check_prop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_check_prop.setGeometry(QtCore.QRect(130, 310, 101, 23))
        self.btn_check_prop.setObjectName("btn_check_prop")
        self.le_total_path = QtWidgets.QLineEdit(self.centralwidget)
        self.le_total_path.setGeometry(QtCore.QRect(380, 270, 181, 20))
        self.le_total_path.setObjectName("le_total_path")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 270, 61, 16))
        self.label_3.setObjectName("label_3")
        self.btn_secret_adb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_secret_adb.setGeometry(QtCore.QRect(790, 270, 111, 23))
        self.btn_secret_adb.setObjectName("btn_secret_adb")
        self.btn_normal_adb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_normal_adb.setGeometry(QtCore.QRect(340, 310, 91, 23))
        self.btn_normal_adb.setObjectName("btn_normal_adb")
        self.btn_onekey_root = QtWidgets.QPushButton(self.centralwidget)
        self.btn_onekey_root.setGeometry(QtCore.QRect(540, 230, 91, 23))
        self.btn_onekey_root.setObjectName("btn_onekey_root")
        self.btn_remount_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remount_file.setGeometry(QtCore.QRect(650, 230, 121, 23))
        self.btn_remount_file.setObjectName("btn_remount_file")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_export_log.setText(_translate("MainWindow", "导出Log日志"))
        self.le_log_export.setText(_translate("MainWindow", "C:\\export_log"))
        self.btn_devices.setText(_translate("MainWindow", "查看设备信息"))
        self.label.setText(_translate("MainWindow", "Log保存地址："))
        self.btn_sys_prop.setText(_translate("MainWindow", "查看系统属性"))
        self.btn_reboot.setText(_translate("MainWindow", "一键重启"))
        self.label_2.setText(_translate("MainWindow", "文件路径："))
        self.btn_push.setText(_translate("MainWindow", "Push"))
        self.btn_clear_info.setText(_translate("MainWindow", "一键清屏"))
        self.btn_check_prop.setText(_translate("MainWindow", "监测属性变化"))
        self.le_total_path.setText(_translate("MainWindow", "system/priv-app/"))
        self.label_3.setText(_translate("MainWindow", "目标地址："))
        self.btn_secret_adb.setText(_translate("MainWindow", "使用加密ADB"))
        self.btn_normal_adb.setText(_translate("MainWindow", "非加密ADB"))
        self.btn_onekey_root.setText(_translate("MainWindow", "一键root"))
        self.btn_remount_file.setText(_translate("MainWindow", "重新挂载文件系统"))

